### ISSUE TITLE
Demon Icon in Garage uses Demon Difficulty Icon rather than Demon Stat Icon

### ISSUE THREAD

**Issue by torzod** [Capeling/Demons-In-Garage-2.2#1]
As the title says, the mod uses the incorrect icon in the garage. The icon used appears to be that of the demon difficulty, but scaled down, which causes its outlines to be much thinner than the other displayed stat icons. Instead, the mod should use the demon stat icon used in player profiles, which has thicker lines, consistent with the other stat icons.
![image](https://github.com/Capeling/Demons-In-Garage-2.2/assets/29359401/8b4b9990-ae6b-488e-b26e-d84f440dcd46)
![image](https://github.com/Capeling/Demons-In-Garage-2.2/assets/29359401/41110bd4-9670-4489-880b-0b7082db25e7)
The difficulty face appears to be GJ_GameSheet03-uhd.png/diffIcon_06_btn_001.png
The stat icon is GJ_GameSheet03-uhd.png/GJ_demonIcon_001.png

**Comment by capeling** [comment]
thanks bestie i didnt know this existed, next update will change the texture
